services:
  # API Service
  - type: web
    name: football-digest-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m app.main
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /health
    autoDeploy: false

  # Background Scheduler Service
  - type: worker
    name: football-digest-scheduler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m app.run_scheduler
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    autoDeploy: false

  # Background Scraper Service
  - type: worker
    name: football-digest-scraper
    env: python
    plan: starter # Specify the plan to ensure proper worker configuration
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && PYTHONPATH=$PYTHONPATH:. python scripts/run_scheduler.py
    # Worker-specific settings
    numInstances: 1
    autoscaling:
      enabled: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONPATH
        value: /opt/render/project/src/backend
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
    # ... rest of your configuration ... 