services:
  - type: web
    name: football-digest-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python -m app.main
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
    # ... rest of your configuration ... 