version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
      - frontend
    networks:
      - frontend
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/football_digest
      - REDIS_URL=redis://redis:6379/0
      - DOMAIN=sogolassos.me
    depends_on:
      - db
      - redis
    networks:
      - backend

  frontend:
    build: ../frontend
    expose:
      - "3000"
    environment:
      - API_URL=https://sogolassos.me/api
    networks:
      - frontend

  scheduler:
    build: .
    command: python scripts/schedule_news_fetch.py
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/football_digest
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=football_digest
    expose:
      - "5432"
    networks:
      - backend

  redis:
    image: redis:7
    expose:
      - "6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  postgres_data:
  redis_data: 